---
- name: Install RabbitMQ
  yum:
    name: kazoo-rabbitmq
    state: latest

- name: Create RabbitMQ Configuration
  template:
    src: rabbitmq.config.j2
    dest: /etc/kazoo/rabbitmq/rabbitmq.config
  notify: Restart Rabbitmq

- name: Start and Enable RabbitMQ 
  service:
    name: kazoo-rabbitmq
    state: started
    enabled: yes


